<?php

class CampForm extends CActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function tableName()
    {
        return '{{camp}}';
    }

    public function rules()
    {
        return [
            ['id', 'unique'],
            ['name', 'validateChild'],
            ['address', 'validateChild'],
            ['age', 'validateChild'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'name' => 'Название лагеря',
            'address' => 'Адрес лагеря',
            'age' => 'Возрост для принятия в лагерь',
            'count' => 'Количество мест в лагере',
        ];
    }

    public function safeAttributes()
    {
        return [
            'name',
            'address',
            'age',
            'count',
        ];
    }

}